### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by mudit3774** [mfateev/uber-java-cadence-samples#15]
Thank you for providing the samples but I am not able to build the project. It seems I am missing something here, but I am unable to find com.uber:cadence-client:0.2.0-SNAPSHOT. Also, should we be using a release version of the client ?

➜  uber-java-cadence-samples git:(master) ./gradlew build -x test

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not find com.uber:cadence-client:0.2.0-SNAPSHOT.
  Searched in the following locations:
      https://plugins.gradle.org/m2/com/uber/cadence-client/0.2.0-SNAPSHOT/maven-metadata.xml
      https://plugins.gradle.org/m2/com/uber/cadence-client/0.2.0-SNAPSHOT/cadence-client-0.2.0-SNAPSHOT.pom
      https://plugins.gradle.org/m2/com/uber/cadence-client/0.2.0-SNAPSHOT/cadence-client-0.2.0-SNAPSHOT.jar
      https://repo.maven.apache.org/maven2/com/uber/cadence-client/0.2.0-SNAPSHOT/maven-metadata.xml
      https://repo.maven.apache.org/maven2/com/uber/cadence-client/0.2.0-SNAPSHOT/cadence-client-0.2.0-SNAPSHOT.pom
      https://repo.maven.apache.org/maven2/com/uber/cadence-client/0.2.0-SNAPSHOT/cadence-client-0.2.0-SNAPSHOT.jar
      file:/Users/mudit.rg/.m2/repository/com/uber/cadence-client/0.2.0-SNAPSHOT/maven-metadata.xml
      file:/Users/mudit.rg/.m2/repository/com/uber/cadence-client/0.2.0-SNAPSHOT/cadence-client-0.2.0-SNAPSHOT.pom
      file:/Users/mudit.rg/.m2/repository/com/uber/cadence-client/0.2.0-SNAPSHOT/cadence-client-0.2.0-SNAPSHOT.jar
  Required by:
      project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
1 actionable task: 1 executed

**Comment by mfateev** [comment]
The problem was due to not having public release of cadence-client. Now it is published to maven central and the build should work. Let us know if it is still broken.

**Comment by mudit3774** [comment]
Thank you for making a public release and changing the build file @mfateev ! 

It works now.

**Comment by mfateev** [comment]
Awesome. Feel free to file issues if you get any problems/questions. Resolving this one.
